name: melos_sample

packages:
  - app
  - model
  - repository

scripts:
  analyze:
    description: analyze
    run: melos exec flutter analyze
  pub_get:
    description: pub get
    run: melos exec flutter pub get

  build_runner:
    description: build runner
    run: melos exec --depends-on=build_runner flutter pub run build_runner build --delete-conflicting-outputs
