name: melos_sample

packages:
  - app
  - model
  - repository

scripts:
  analyze:
    description: analyze
    run: melos exec flutter analyze
  pub_get:
    description: pub get
    run: melos exec flutter pub get
